namespace ErrorCraft;

/// <summary>
/// Defines a contract for objects that can be mapped to a Problem Details (RFC 9457) response.
/// </summary>
public interface IProblemDetailsSource
{
    /// <summary>
    /// A URI reference [RFC3986] that identifies the problem type.
    /// When this member is not present, its value is assumed to be "about:blank".
    /// </summary>
    string Type => "about:blank";

    /// <summary>
    /// The HTTP status code ([RFC9110], Section 15) generated by the origin server for this occurrence of the problem.
    /// </summary>
    int Status { get; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
    /// </summary>
    string Title { get; }
}
